version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lets build and push image
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            echo $version
            docker build -t nitinitesh/todo-app:$version .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push nitinitesh/todo-app:$version

  Update_menifest:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Updating Menifest file 
          command: |
            TAG=$CIRCLE_BUILD_NUM
            ((TAG--))
            git clone https://github.com/NitinItesh/Demo_Cloud_Kube_Manifest.git
            git config --global user.email "niteshsharma.me@gmail.com"
            git config --global user.name "Nitesh Sharma"
            cd Demo_Cloud_Kube_Manifest
            sed -i "s/build-.*/build-$TAG/g" menifest/deployment.yaml
            git add .
            git commit -m "new build with imgTag build-$TAG"
            git config credential.helper 'cache --timeout=120'
            git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/NitinItesh/Demo_Cloud_Kube_Manifest.git main 
workflows:
  GitOpsflow:
    jobs:
      - build_and_push
      - Update_menifest:
          requires:
            - build_and_push
      


